from . import start
from . import begin
from . import back
from . import reflink
from . import score
from . import partners
from . import tasks
from . import clicker
from . import wallet
from . import top
from . import ru_channel
from . import en_channel
from . import ru_chat
from . import en_chat
from . import twitter